name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python requirements
        run: pip install -r backend/requirements.txt

      - name: Install Node modules
        run: npm install

      - name: Check GH_TOKEN presence
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN not found!"
            exit 1
          else
            echo "GH_TOKEN is set (masked)"
          fi

      - name: Build the EXE
        run: npm run dist

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: 지유_근무_스케줄러_EXE
          path: dist/*.exe
